services:
  web:
    container_name: ziptransfer-web
    build: frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:${WEB_SERVER_FORWARD_PORT:-9001}:9001"
    depends_on:
      - api
    # If you use caddy as a container uncomment the following
    #networks:
      #- ziptransfer-net

  api:
    container_name: ziptransfer-api
    build: backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:${BACKEND_FORWARD_PORT:-9002}:9002"
    volumes:
      - api_data:/app/data
    # If you use caddy as a container uncomment the following
    #networks:
      #- ziptransfer-net

volumes:
  api_data:

# If you use caddy as a container uncomment the following
#networks:
  #ziptransfer-net:
    #external: true
