version: "3.8"

services:
  web:
    build: frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:${WEB_SERVER_FORWARD_PORT:-9001}:9001"
    depends_on:
      - api

  api:
    build: backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:${BACKEND_FORWARD_PORT:-9000}:9000"
    volumes:
      - api_data:/app/data

volumes:
  api_data:
